introduce max_block_value_to_verify in constraints config
chainbound/helix pull request #23
Opened 2024-11-11 06:06 UTC by gd-0

- introduce new constraints config param: `max_block_value_to_verify`
- if the block value is greater than this field, inclusion constraints are not verified in `submit_block` and `get_header_with_proofs`

Reasoning behind this is that we don't want validators to miss out on big ETH rewards on mainnet while testing inclusion preconf blocks.

2024-11-11 10:01 UTC, thedevbirb requested changes
Thanks for the PR! Here are some minor changes that should be done in our opinion.

Once you've done these, can you run `just fmt` and make sure `just fmt-check` and `just clippy` introduced in https://github.com/gattaca-com/helix/pull/48 run without errors?

2024-11-11 10:01 UTC, thedevbirb commented on crates/api/src/builder/api.rs
> +                    "block value is greater than max value to verify, skipping inclusion proof verification",
```suggestion
                    "block value is greater than max value to verify, inclusion proof verification and saving is skipped",
```

2024-11-11 10:01 UTC, thedevbirb commented on crates/api/src/proposer/api.rs
> +                            "block value is greater than max value to verify, skipping inclusion proof check in get_header_with_proofs",
fyi inclusion proofs are not verified in the `get_header_with_proofs` call on the relay side.

2024-11-11 10:01 UTC, thedevbirb commented on crates/api/src/builder/api.rs
> +        }
The function to verify and save inclusion proofs is great ty, but can we move this if check outside the function, before it is called? So that calling this functions means doing these steps regardless of the input.

2024-11-11 10:01 UTC, thedevbirb commented on crates/api/src/proposer/api.rs
> +                    }
I think this check can be done way earlier, so the flow can look like this:
- get the bid
- save trace to DB
- do the bid value check -- if it's satisfied, then do an early return since we the `submit_block_with_proofs` code doesn't save or verify proofs in that scenario
- if it's not satisfied, continue with the usual steps.

2024-11-11 10:01 UTC, thedevbirb commented on crates/common/src/config.rs
>  }
This change here results in the code not compiling because this field is missing in the implementation of the `Default` trait for `ConstraintsApiConfig`. Can you remove the `serde` attribute and add the default value `None` in the function below?

2024-11-11 12:33 UTC, gd-0 commented on crates/api/src/proposer/api.rs
> +                            "block value is greater than max value to verify, skipping inclusion proof check in get_header_with_proofs",
ah right yeah comment was a bit misleading here - have adjusted the comment

2024-11-11 15:23 UTC, thedevbirb requested changes
Tested on the devnet and works good, a minor change is needed to make tests compile.

2024-11-11 15:23 UTC, thedevbirb commented on crates/api/src/builder/api.rs
> +            }
What do you think of inverting the condition? Imo easier to read compared to a double negation
```rs
        let should_verify_and_save_inclusion_proofs = api
            .relay_config
            .constraints_api_config
            .max_block_value_to_verify_wei
            .map_or(true, |max_block_value_to_verify| payload.value() <= max_block_value_to_verify);
        if should_verify_and_save_inclusion_proofs {
            ...
         } else {
             info!("block value is greater than ...")
         }
```

2024-11-11 15:23 UTC, thedevbirb commented on crates/api/src/test_utils.rs
> +        Arc::new(Default::default()),
This makes tests not compile, it should be
```suggestion
        Default::default(),
```

2024-11-12 09:17 UTC, thedevbirb approved these changes

2024-11-12 09:17 UTC, merged